/* eslint-disable react-hooks/set-state-in-effect */
"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { api, ApiProblem, idempotencyKey, Message, Ticket } from "@/lib/api";
import { MessageList } from "./message-list";
export function StaffWorkspace() {
  const [tickets, setTickets] = useState<Ticket[]>([]), [active, setActive] = useState<Ticket | null>(null), [messages, setMessages] = useState<Message[]>([]), [filter, setFilter] = useState("all"), [search, setSearch] = useState(""), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  const refresh = useCallback(async () => { const rows = await api<Ticket[]>(`/staff/tickets${filter === "all" ? "" : `?status=${filter}`}`); setTickets(rows); if (active) setActive(rows.find((x) => x.id === active.id) ?? null); }, [filter, active]);
  useEffect(() => { refresh().catch(() => setError("Ticket queue unavailable.")); }, [filter]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { if (active) api<Message[]>(`/conversations/${active.conversation_id}/messages?limit=100`).then(setMessages).catch(() => setError("Conversation unavailable.")); }, [active]);
  const shown = useMemo(() => tickets.filter((x) => JSON.stringify(x).toLowerCase().includes(search.toLowerCase())), [tickets, search]);
  async function action(name: string, content?: string) { if (!active) return; setBusy(true); setError(""); try { const updated = await api<Ticket>(`/staff/tickets/${active.id}/${name}`, { method: "POST", headers: { "Idempotency-Key": idempotencyKey(`ticket-${active.id}-${name}`) }, body: JSON.stringify({ version: active.version, content }) }); setActive(updated); await refresh(); setMessages(await api<Message[]>(`/conversations/${active.conversation_id}/messages?limit=100`)); } catch (problem) { setError((problem as ApiProblem).status === 409 ? "This ticket changed. The latest version has been loaded." : (problem as ApiProblem).message); await refresh(); } finally { setBusy(false); } }
  function send(event: FormEvent<HTMLFormElement>, name: "reply" | "note") { event.preventDefault(); const form = new FormData(event.currentTarget), content = String(form.get("content") ?? "").trim(); if (content) action(name, content); event.currentTarget.reset(); }
  return <div className="workspace staff"><aside className="sidebar"><div className="brand"><span>N</span><div><strong>NovaCart</strong><small>Support workspace</small></div></div><label className="search">Search tickets<input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Order, issue, status"/></label><label className="search">Queue status<select value={filter} onChange={(e) => setFilter(e.target.value)}><option value="all">All tickets</option><option value="OPEN">Open</option><option value="IN_PROGRESS">In progress</option><option value="RESOLVED">Resolved</option><option value="CLOSED">Closed</option></select></label><nav aria-label="Ticket queue">{shown.map((ticket) => <button className={active?.id === ticket.id ? "ticket-row active" : "ticket-row"} key={ticket.id} onClick={() => setActive(ticket)}><span><strong>{ticket.reason_code.replaceAll("_", " ")}</strong><small>{ticket.priority} · {ticket.status}</small></span><i>{ticket.version}</i></button>)}</nav></aside><main className="ticket-detail">{active ? <><header className="topbar"><div><p className="eyebrow">Ticket {active.id.slice(0, 8)}</p><h1>{active.reason_code.replaceAll("_", " ")}</h1><p>{active.priority} priority · {active.status}</p></div><div className="actions"><button disabled={busy} onClick={() => action("claim")}>Claim</button><button disabled={busy} onClick={() => action("resolve")}>Resolve</button><button disabled={busy} onClick={() => action("close")}>Close</button><button disabled={busy} onClick={() => action("return_to_ai")}>Return to AI</button></div></header>{error && <div className="alert">{error}</div>}<section className="summary-card"><h2>Grounded summary</h2><pre>{JSON.stringify(active.summary, null, 2)}</pre></section><section className="staff-thread"><h2>Conversation history</h2><MessageList messages={messages}/></section><div className="staff-composers"><form onSubmit={(e) => send(e, "reply")}><label>Public reply<textarea name="content" required maxLength={4000}/></label><button className="primary" disabled={busy}>Send to customer</button></form><form className="private-note" onSubmit={(e) => send(e, "note")}><label>Private internal note<textarea name="content" required maxLength={4000}/></label><p>Only Support and Admin staff can see this note.</p><button disabled={busy}>Add private note</button></form></div></> : <div className="empty"><h1>Select a ticket</h1><p>Review customer context and take ownership from the queue.</p></div>}</main></div>;
}
