"""add hybrid knowledge retrieval

Revision ID: cca2768466e7
Revises: 0bde15eda497
Create Date: 2026-09-02 18:06:33.412046
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision: str = "cca2768466e7"
down_revision: str | None = "0bde15eda497"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_chunk_metadata_org_id", "chunk_metadata", ["organization_id", "id"]
    )
    op.create_table(
        "citation_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("document_version_id", sa.UUID(), nullable=False),
        sa.Column("chunk_id", sa.UUID(), nullable=False),
        sa.Column("source_title", sa.String(length=240), nullable=False),
        sa.Column("language", sa.String(length=5), nullable=False),
        sa.Column("section_anchor", sa.String(length=300), nullable=True),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("snippet", sa.Text(), nullable=False),
        sa.Column("chunk_checksum", sa.String(length=64), nullable=False),
        sa.Column(
            "retrieved_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "chunk_id"],
            ["chunk_metadata.organization_id", "chunk_metadata.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "document_id"],
            ["knowledge_documents.organization_id", "knowledge_documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "document_version_id"],
            ["document_versions.organization_id", "document_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_citation_records_organization_id"),
        "citation_records",
        ["organization_id"],
        unique=False,
    )
    op.add_column("chunk_metadata", sa.Column("text", sa.Text(), nullable=True))
    op.add_column("chunk_metadata", sa.Column("language", sa.String(length=5), nullable=True))
    op.add_column("chunk_metadata", sa.Column("page_number", sa.Integer(), nullable=True))
    op.add_column("chunk_metadata", sa.Column("embedding", Vector(32), nullable=True))
    op.add_column(
        "chunk_metadata", sa.Column("search_vector", postgresql.TSVECTOR(), nullable=True)
    )
    op.execute(
        "UPDATE chunk_metadata AS c SET text = '', language = v.locale, "
        "embedding = array_fill(0::real, ARRAY[32])::vector, "
        "search_vector = to_tsvector('simple', '') FROM document_versions AS v "
        "WHERE v.id = c.document_version_id"
    )
    op.alter_column("chunk_metadata", "text", nullable=False)
    op.alter_column("chunk_metadata", "language", nullable=False)
    op.alter_column("chunk_metadata", "embedding", nullable=False)
    op.alter_column("chunk_metadata", "search_vector", nullable=False)
    op.create_index(
        "ix_chunk_metadata_search_vector",
        "chunk_metadata",
        ["search_vector"],
        postgresql_using="gin",
    )
    op.create_index(
        "ix_chunk_metadata_embedding_hnsw",
        "chunk_metadata",
        ["embedding"],
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.add_column(
        "document_versions",
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "READY",
                "FAILED",
                "SUPERSEDED",
                name="ingestionstatus",
                native_enum=False,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "document_versions", sa.Column("source_filename", sa.String(length=240), nullable=True)
    )
    op.add_column(
        "document_versions", sa.Column("media_type", sa.String(length=100), nullable=True)
    )
    op.add_column("document_versions", sa.Column("raw_content", sa.LargeBinary(), nullable=True))
    op.add_column("document_versions", sa.Column("error_code", sa.String(length=80), nullable=True))
    op.add_column("knowledge_documents", sa.Column("title", sa.String(length=240), nullable=True))
    op.add_column(
        "knowledge_documents", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.execute(
        "UPDATE document_versions SET status = 'PENDING', source_filename = 'legacy.txt', "
        "media_type = 'text/plain', raw_content = ''::bytea"
    )
    op.alter_column("document_versions", "status", nullable=False)
    op.alter_column("document_versions", "source_filename", nullable=False)
    op.alter_column("document_versions", "media_type", nullable=False)
    op.alter_column("document_versions", "raw_content", nullable=False)
    op.execute("UPDATE knowledge_documents SET title = slug")
    op.alter_column("knowledge_documents", "title", nullable=False)
    op.execute("ALTER TABLE citation_records ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE citation_records FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_isolation ON citation_records USING (organization_id = "
        "NULLIF(current_setting('app.organization_id', true), '')::uuid) WITH CHECK "
        "(organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_citation_records_organization_id"), table_name="citation_records")
    op.drop_table("citation_records")
    op.drop_column("knowledge_documents", "deleted_at")
    op.drop_column("knowledge_documents", "title")
    op.drop_column("document_versions", "error_code")
    op.drop_column("document_versions", "raw_content")
    op.drop_column("document_versions", "media_type")
    op.drop_column("document_versions", "source_filename")
    op.drop_column("document_versions", "status")
    op.drop_index("ix_chunk_metadata_embedding_hnsw", table_name="chunk_metadata")
    op.drop_index("ix_chunk_metadata_search_vector", table_name="chunk_metadata")
    op.drop_constraint("uq_chunk_metadata_org_id", "chunk_metadata", type_="unique")
    op.drop_column("chunk_metadata", "search_vector")
    op.drop_column("chunk_metadata", "embedding")
    op.drop_column("chunk_metadata", "page_number")
    op.drop_column("chunk_metadata", "language")
    op.drop_column("chunk_metadata", "text")
    # ### end Alembic commands ###
